[17기 김채현] ResumeMainView
wecode-bootcamp-korea/17-2nd-WantUs-backend pull request #10
Opened 2021-03-07 06:51 UTC by JELLO-Kim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- ResumeMainView 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 기본제공이력서 목록 GET
- 기본제공이력서 POST
- login_decorator가 있는 상황에서 unittest 구현 완료

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 미완성이지만.. 백업용을위해 올렸습니다.. 흐린눈으로 봐주시고 라벨은 달지 않을께요..... 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-09 15:52 UTC, JELLO-Kim commented
tests.py 작성법이 잘못됐습니다! 수정해서 다시 라벨 붙이겠습니당!

2021-03-10 04:46 UTC, Kang-kyunghun requested changes

2021-03-10 04:46 UTC, Kang-kyunghun commented on resume/views.py
> +        user = User.objects.get(id=4)
user 변수가 반복 됩니다.

2021-03-10 04:46 UTC, Kang-kyunghun commented on resume/views.py
> +        return JsonResponse({'message' : 'SUCCESS', 'result' : resume.id}, status=201)
전체적으로 이야기 필요

2021-03-10 04:46 UTC, Kang-kyunghun commented on resume/views.py
> +            return JsonResponse({'message' : 'INVALID_RESUME'}, status=400)
이 부분은 다른 PR에 있는 건가요? 
그러면 이 부분은 삭제해 주시고 push 해주세요.

2021-03-10 04:46 UTC, Kang-kyunghun commented on resume/tests.py
> +        self.assertEqual(response.status_code, 400)
url 수정하고 test 다시 안 돌려 보셨네요~~ test는 수정 전에 url 입니다.

2021-03-10 05:12 UTC, chaehyun-dev commented on resume/views.py
> +        user = User.objects.get(id=4)
죄송합니다...ㅠㅠ

2021-03-10 05:12 UTC, JELLO-Kim commented on resume/views.py
> +        return JsonResponse({'message' : 'SUCCESS', 'result' : resume.id}, status=201)
죄송합니다.. user 반복되고 하드코딩한 부분 수정했습니다!

2021-03-10 05:12 UTC, JELLO-Kim commented on resume/views.py
> +            return JsonResponse({'message' : 'INVALID_RESUME'}, status=400)
깔끔하게 정리하겠습니다!

2021-03-10 05:13 UTC, JELLO-Kim commented on resume/tests.py
> +        self.assertEqual(response.status_code, 400)
넵 죄송합니다ㅠㅠ

2021-03-10 15:52 UTC, Kang-kyunghun requested changes

2021-03-10 15:52 UTC, Kang-kyunghun commented on resume/views.py
> +            } for resume in resumes.union(resume_files).order_by('-update_at')]
values와 union을 사용하지 않고, table간에 관계만을 가지고 구현하기 힘든 구조인가요?
그렇지 않으면, 이 둘을 사용하지 않고 구현해 보세요.

2021-03-11 00:41 UTC, JELLO-Kim commented on resume/views.py
> +            } for resume in resumes.union(resume_files).order_by('-update_at')]
두개 table의 field 종류&갯수가 달라 바로 union으로 합칠수가 없었습니다ㅠㅠ 그래서 values로 합치고자 하는 공통된 field들만 뽑았고, "기본이력서"와 "업로드된 이력서" 모두를 합쳐 "수정시간 순"으로 정렬시켜 데이터를 보내드리는 과정이었습니다!
사용하지 않는 방법도 생각해보겠습니당. 감사합니다!

2021-03-11 08:06 UTC, Kang-kyunghun commented
LGTM~~ 고생하셨습니다.~~

2021-03-11 08:06 UTC, merged