[17기 장성준] PostingListView 생성, filtering 완료, unittest 완료, 통신 완료
wecode-bootcamp-korea/17-2nd-WantUs-backend pull request #15
Opened 2021-03-09 18:01 UTC by ique-coder

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- PostingListView 생성, filtering 완료, unittest 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- PostingListView 생성
  - GET
  - pagination 적용
  - 불러올때 tag, location에 대한 값들을 다 줌
- filtering 완료
  - 다중 필터링
  - loctions, tags
  - category
- sorting 완료
  - new
  - best
  - reward
- unittest 완료

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-10 08:44 UTC, Kang-kyunghun requested changes

2021-03-10 08:44 UTC, Kang-kyunghun commented on posting/views.py
> +                    .order_by(SORTING_DICT[sorting])
query가 얼마나 줄었는지 올려 주세요~

2021-03-10 08:44 UTC, Kang-kyunghun commented on posting/views.py
> +        }
여기도 posting과 상관 없이 보내주는 meta data인거죠?
meta data에 대해서 프론트랑 얘기해 보시면 좋을 것 같습니다.

2021-03-10 08:44 UTC, Kang-kyunghun commented on posting/views.py
> +            q.add(Q(company_detail__company__id__in=company_location_list), q.AND)
front에 data를 받은 뒤 불필요한 data 가공 과정을 거치는 것 같습니다.
정확한 설명이 필요 할 것 같습니다.

2021-03-11 02:40 UTC, ique-coder commented on posting/views.py
> +                    .order_by(SORTING_DICT[sorting])
단순 줄수로도 200줄에서 44줄로 줄었습니다!

2021-03-11 02:40 UTC, ique-coder commented on posting/views.py
> +                    .order_by(SORTING_DICT[sorting])
<img width="362" alt="스크린샷 2021-03-11 오전 11 39 19" src="https://user-images.githubusercontent.com/51706303/110727422-97c8fb80-825e-11eb-87c5-9d76eb444740.png">
<img width="618" alt="스크린샷 2021-03-11 오전 11 39 03" src="https://user-images.githubusercontent.com/51706303/110727423-9992bf00-825e-11eb-8f31-1b3c5d33e160.png">

2021-03-11 02:41 UTC, ique-coder commented on posting/views.py
> +        }
네네 밎습니다..ㅠㅠ

2021-03-11 02:41 UTC, ique-coder commented on posting/views.py
> +            q.add(Q(company_detail__company__id__in=company_location_list), q.AND)
넵 대면으로 이야기 드리겠습니다!

2021-03-11 11:02 UTC, jamessoun93 approved these changes
LGTM

2021-03-11 11:02 UTC, merged