[17기 김채현] Add: ResumePartialView
wecode-bootcamp-korea/17-2nd-WantUs-backend pull request #20
Opened 2021-03-10 14:57 UTC by JELLO-Kim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Add: ResumePartialView		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 하나의 이력서를 선택해 상세 내용을 확인하는 view (ResumePartialView) 작성
- 이력서 안에는 user의 정보 & 경력사항(career / list형태) & 학력사항(education / list형태) & 언어자격증(language / list형태) 에 대한 내용이 들어있습니다.
- unittest 구현 (success / 토큰의 유저와 이력서 주인 불일치 시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- GET 과 DELETE만 하기로 했는데 DELETE 는 "ResumePartialDetailView"로 따로 작성하겠습니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [X] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-10 15:59 UTC, Kang-kyunghun requested changes

2021-03-10 15:59 UTC, Kang-kyunghun commented on resumepatch.json
> +}
필요 없는 파일로 보입니다.
제거해 주세요.

2021-03-10 15:59 UTC, Kang-kyunghun commented on resume/views.py
> +        resume              = Resume.objects.get(id=resume_id)
get을 사용할 때 발생 할 수 있는 예외 처리 추가해 주세요.

2021-03-10 15:59 UTC, Kang-kyunghun commented on resume/tests.py
> +
예외처리 추가하고 test 추가해 주세요.

2021-03-11 00:41 UTC, JELLO-Kim commented on resumepatch.json
> +}
넵! 죄송합니다!

2021-03-11 01:06 UTC, JELLO-Kim commented on resume/views.py
> +        resume              = Resume.objects.get(id=resume_id)
get으로 받는 값인 resume_id가 path parameter로 들어오는 값이라 단일 id 한개에 대한 값이 아니면 Not Found(404)가 뜨는데 제 view 안에서 잡을수 있나요....?

2021-03-11 01:06 UTC, JELLO-Kim commented on resume/tests.py
> +
위의 에러에 대한건 못잡았지만 추가적으로 없는 resume의 id를 path parameter로 받았을시 뜨는 Resume.DoesNotExist 에러에 대한 것을 추가하였습니다!

2021-03-11 06:22 UTC, Kang-kyunghun commented
고생 많았어요~!!!

2021-03-11 06:23 UTC, merged