[17기 장성준] ProfileView 작성 완료
wecode-bootcamp-korea/17-2nd-WantUs-backend pull request #4
Opened 2021-03-03 12:24 UTC by ique-coder

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- ProfileView 작성 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-ProfileView 생성
- GET 생성
- PATCH 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-08 08:04 UTC, Kang-kyunghun requested changes

2021-03-08 08:04 UTC, Kang-kyunghun commented on user/views.py
> +from posting.models import (
컨벤션 맞춰 주세요

2021-03-08 08:04 UTC, Kang-kyunghun commented on user/views.py
> +        }
occupation에서 skill까지 모두 로그인 한 user의 정보일 것 같은데, user 정보를 가지고 조회하는 것이 아닌 해당 필드의 모든 정보를 가져오는 것으로 보입니다.

2021-03-08 08:04 UTC, Kang-kyunghun commented on user/views.py
> +
이 부분은 여러 값들을 가져올 수 있어서 작성한 부분인가요?

2021-03-09 03:11 UTC, ique-coder commented on user/views.py
> +from posting.models import (
넵! 감사합니다😂

2021-03-09 03:15 UTC, ique-coder commented on user/views.py
> +        }
아 넵!

GET 메소드는 Frontend에서 프로필을 작성할 때 필요한 값들을 전달하는 역할을 합니다!

직무, 직군, 경력(신입, 1년차 등..), 스킬(CSS, HTML 등..)을 선택해서 작성을 해야 하기에
Backend에서 그 값들을 전달하고 Frontend는 그 값들을 select 하게 되는데 그 과정에서 모든 항목들을 보내주고 있는 로직입니다😎

2021-03-09 03:17 UTC, ique-coder commented on user/views.py
> +
네 맞습니다!

한 유저가 여러 스킬(CSS, HTML, JS, React 등등..)을 가질 수 있어서 그렇게 하였고,
한 유저가 여러 직무(파이썬 개발자, 장고 개발자, 웹 개발자 등등..)을 가질 수 있어서 이렇게 로직을 짯습니다!

2021-03-11 04:52 UTC, Kang-kyunghun commented
LGTM!!

2021-03-11 04:54 UTC, Kang-kyunghun commented
LGTM~!!!

2021-03-11 04:54 UTC, merged