[17기 김채현] MainView GET
wecode-bootcamp-korea/17-2nd-WantUs-backend pull request #6
Opened 2021-03-05 11:23 UTC by JELLO-Kim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- MainView GET
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 유저에게 보이는 mainpage GET 작성 (MainView)
- url 설정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-05 12:15 UTC, JELLO-Kim commented
convention이 엉망이라.. 고치고 다시 라벨 붙이겠습니다..

2021-03-08 08:14 UTC, Kang-kyunghun requested changes

2021-03-08 08:14 UTC, Kang-kyunghun commented on posting/tests.py
> +        self.assertEqual(response.status_code, 400)
status code 뿐만 아니라, json data도 test에 포함시켜 주세요.

2021-03-08 08:14 UTC, Kang-kyunghun commented on posting/views.py
> +        postings = set_postings.order_by('-like_num')[: LIST_LIMIT_NUMBER]
```suggestion
        postings = set_postings.order_by('-like_num')[:LIST_LIMIT_NUMBER]
```

2021-03-08 08:14 UTC, Kang-kyunghun commented on posting/views.py
> +
postings에 대한 for문이 3번 돌고 있는데, 한 번의 for문으로 합칠 수 없을까요?

2021-03-08 08:14 UTC, Kang-kyunghun commented on posting/views.py
> +                            'job_category__occupation').all()
query가 많이 줄었나요?? 결과 있으면 첨부해 주세요.

2021-03-08 11:39 UTC, JELLO-Kim commented on posting/views.py
> +        postings = set_postings.order_by('-like_num')[: LIST_LIMIT_NUMBER]
호... 감사합니다!

2021-03-08 11:39 UTC, JELLO-Kim commented on posting/tests.py
> +        self.assertEqual(response.status_code, 400)
넵! 수정하겠습니다.

2021-03-08 11:39 UTC, JELLO-Kim commented on posting/views.py
> +
그생각은 못했는데!! 수정해보겠습니다!

2021-03-08 11:40 UTC, JELLO-Kim commented on posting/views.py
> +
아그런데 첫번째꺼랑 두번째&세번째는 postings 리스트에 있는 조건이 달라서요...! 두개로 줄여보겠습니당!

2021-03-08 11:40 UTC, JELLO-Kim commented on posting/views.py
> +                            'job_category__occupation').all()
네~~🙌

2021-03-09 09:30 UTC, JELLO-Kim commented on posting/views.py
> +
결국 다시 돌아갔습니다...

posting의 for문을 3개에서 2개로 줄이려니까

new = [[{새로운 공고 낸 회사 1}, {새로운 공고1}], [{새로운 공고 낸 회사2}, {새로운 공고2}], [{새로운 공고 낸 회사 3}, {새로운 공고3}], [{새로운 공고 낸 회사4}, {새로운 공고4}]]
이렇게 출력이 되어서 회사와 공고의 list를 분리하기 위해

new_company = []
new_posting = []
for new in new_list:
    new_company.append(new[0])
    new_posting.append(new[1])

로 다시 각각의 list에 넣어주는 작업을 했었습니다ㅠㅠ 결국엔 for문이 다시 3개...

2021-03-09 15:38 UTC, Kang-kyunghun requested changes

2021-03-09 15:38 UTC, Kang-kyunghun commented on wantus/urls.py
> +    path('cv', include('resume.urls')),
resume의 app의 urlpatern 시작이 cv인 이유가 있을까요?

2021-03-09 15:38 UTC, Kang-kyunghun commented on posting/tests.py
> +        self.assertEqual(response.status_code, 400)
test 결과의 json data는 실제 결과로 나와야 되는 data 입니다. view 코드를 그대로 복사 붙여 넣기 하셨네요. LIST_LIMIT_NUMBER 의 띄어쓰기가 view 코드 수정 전이랑 똑같습니다...

2021-03-09 15:38 UTC, Kang-kyunghun commented on resume/urls.py
> +    path('/list', ResumeMainView.as_view()),
resume도 product랑 비슷하게 생각한다면, list라는 url이 꼭 필요할 것 같지는 않습니다.

2021-03-09 15:38 UTC, Kang-kyunghun commented on resume/views.py
> +                )
하드코딩 부분은 만나서 얘기해 봐요

2021-03-09 15:38 UTC, Kang-kyunghun commented on resume/views.py
> +    @login_decorator
한 칸 띄어 주세요.

2021-03-09 15:41 UTC, JELLO-Kim commented on wantus/urls.py
> +    path('cv', include('resume.urls')),
원티드에서.. 그렇게 시작해서 사용했었습니다.. 저희 프로젝트니까 다시 맞추겠습니다!

2021-03-09 15:41 UTC, JELLO-Kim commented on resume/urls.py
> +    path('/list', ResumeMainView.as_view()),
넵! 수정하겠습니다!

2021-03-09 15:42 UTC, JELLO-Kim commented on resume/views.py
> +                )
넵!!!

2021-03-09 15:42 UTC, JELLO-Kim commented on resume/views.py
> +    @login_decorator
넵!!!

2021-03-09 15:45 UTC, JELLO-Kim commented on posting/tests.py
> +        self.assertEqual(response.status_code, 400)
앗....... 제가 잘못이해하고있었네요ㅠㅠ 죄송합니다 수정하겠습니다! 띄어쓰기는..대답해놓고 반영을 제대로 안했네요... 죄송합니다!!!!!!

2021-03-09 16:50 UTC, JELLO-Kim commented on posting/views.py
> +                            'job_category__occupation').all()
# 1. select_related 를 사용하지 않았을 경우
```
set_postings = Posting.objects.annotate(like_num=Count('like').all()
```
만 사용했을 경우 **총 72번**의 db hit 발생

# 2. 위와 같이 select_related 를 사용했을 경우
총 **32**번의 db hit 발생
<줄이지 못한 부분> 
- annotate로 like 갯수 세어줄 때
```
(0.000) SELECT COUNT(*) AS `__count` FROM `likes` WHERE (`likes`.`posting_id` = 14 AND `likes`.`posting_id` = 14); args=(14, 14)
```
- `posting의 정참조->정참조(company)->company의 역참조인 company_image중 첫번째` 를 찾을때
```
(0.000) SELECT (1) AS `a` FROM `company_images` WHERE `company_images`.`company_id` = 17 LIMIT 1; args=(17,)
(0.000) SELECT `company_images`.`id`, `company_images`.`company_id`, `company_images`.`image_url` FROM `company_images` WHERE `company_images`.`company_id` = 17 ORDER BY `company_images`.`id` ASC LIMIT 1; args=(17,)
```
<img src="https://user-images.githubusercontent.com/71021769/110506772-bfc33c80-8142-11eb-87bf-efe6b092fa69.png">

이렇게 정리해 봤습니다...!!!

2021-03-10 03:39 UTC, JELLO-Kim commented on resume/views.py
> +    @login_decorator
이부분도 ReseumeView PR에서 수정하겠습니다.

2021-03-10 03:40 UTC, JELLO-Kim commented on resume/views.py
> +                )
아까 수정하기로 한 부분은 ResumeView PR에서 반영하겠습니다!

2021-03-10 03:41 UTC, JELLO-Kim commented on resume/urls.py
> +    path('/list', ResumeMainView.as_view()),
이부분도 ResumeView PR에서 수정하겠습니다!

2021-03-10 06:52 UTC, Kang-kyunghun commented
LGTM!!!!!!!!!!!!!

2021-03-10 06:52 UTC, merged