[17기 강현수]: PostingDetailView GET 작성완료 및 UnitTest 완료
wecode-bootcamp-korea/17-2nd-WantUs-backend pull request #7
Opened 2021-03-05 11:43 UTC by exgaze

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- PostingDetailView Get 작성 완료
- UnitTest 수행
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-08 08:26 UTC, soheon-lee commented
@exgaze unit test detail json 모두 추가 후 다시 push  부탁드립니다 :)

2021-03-10 02:59 UTC, Kang-kyunghun requested changes

2021-03-10 02:59 UTC, Kang-kyunghun commented on posting/views.py
> +
컨벤션 맞춰 주세요.

2021-03-10 02:59 UTC, Kang-kyunghun commented on posting/views.py
> +            if user == None:
```suggestion
            if user is None:
```
None을 판별할 때는 is를 사용합니다.

2021-03-10 02:59 UTC, Kang-kyunghun commented
위의 두 부분 수정하시면 merge 하겠습니다.

2021-03-10 03:04 UTC, exgaze commented on posting/views.py
> +            if user == None:
두가지 모두 수정해서 올리겠습니다!

2021-03-10 04:37 UTC, Kang-kyunghun commented
LGTM!!!

2021-03-10 04:37 UTC, merged