[17기 강현수]Detail page 무한 스크롤 구현 완료 및 Unittest완료
wecode-bootcamp-korea/17-2nd-WantUs-backend pull request #8
Opened 2021-03-06 11:27 UTC by exgaze

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Detail page 무한 스크롤 구현
- Unittest 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Pagination을 이용한 무한스크롤 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-09 02:53 UTC, Kang-kyunghun requested changes

2021-03-09 02:53 UTC, Kang-kyunghun commented on posting/tests.py
> +        self.assertEqual(response.status_code, 404)
json data 추가해 주세요.

2021-03-09 02:53 UTC, Kang-kyunghun commented on wantus/test_runner.py
> +        pass
이 파이썬 파일의 용도는 무엇인가요?
프로젝트에 필요없는 파일은 제거해 주세요.

2021-03-09 02:53 UTC, Kang-kyunghun commented on wantus/settings_test.py
> +TEST_RUNNER = 'wantus.test_runner.TestRunner'
필요없는 파일은 제거해 주세요.

2021-03-09 02:53 UTC, Kang-kyunghun commented on posting/views.py
> +        PER_PAGE = 4
per page를 front에서 받지 않고, 백엔드에서 지정해 주나요?

2021-03-09 02:53 UTC, Kang-kyunghun commented on posting/views.py
> +                        'img': [image.image_url for image in posting_related.company_detail.company.companyimage_set.all()][0],
```suggestion
                        'image': [image.image_url for image in posting_related.company_detail.company.companyimage_set.first(),
```

2021-03-09 02:53 UTC, Kang-kyunghun commented on posting/views.py
> +                        'like': posting_related.like_set.all().count(),
```suggestion
                        'like': posting_related.like_set.count(),
```
all()을 안 하고 바로 count()을 사용할 수 있습니다. 확인해 보세요.

2021-03-09 03:04 UTC, exgaze commented on wantus/test_runner.py
> +        pass
테스트 db 대신 로컬 db로 테스트를 진행하고자 할 때 필요한 파일입니다. 테스트 db에 한글 문자가 들어가지 않는 문제를 해결하면 지우겠습니다.(로컬 db에는 한글 문자가 들어가는 것으로 보아, 추가적인 탐구를 해야할 것 같습니다.)

2021-03-09 03:04 UTC, exgaze commented on wantus/settings_test.py
> +TEST_RUNNER = 'wantus.test_runner.TestRunner'
위와 같은 역할을 하는 파일입니다.

2021-03-09 03:05 UTC, exgaze commented on posting/views.py
> +        PER_PAGE = 4
한번의 스크롤에 몇개씩 데이터가 들어가야 할지 둘이 같이 합의하고, 백엔드에서 제한을 걸기로 했습니다

2021-03-09 03:06 UTC, exgaze commented on posting/views.py
> +                        'img': [image.image_url for image in posting_related.company_detail.company.companyimage_set.all()][0],
수정하겠습니다!

2021-03-09 03:06 UTC, exgaze commented on posting/views.py
> +                        'like': posting_related.like_set.all().count(),
넵, 감사합니다!

2021-03-09 15:50 UTC, Kang-kyunghun requested changes

2021-03-09 15:50 UTC, Kang-kyunghun commented on posting/urls.py
> +    path('/pagination/<int:posting_id>', DetailPaginationView.as_view()),
DetailPaginationView의 역할이 posting의 상세 페이지 내부의 연과 poating만을 위한 view라면, view의 이름은 'RelatedPostingView'로 바꾸고 url도 /<int:posting_id>/related-posting 으로 하는 것이 더 RESTfull 하다고 생각됩니다.

2021-03-09 15:50 UTC, Kang-kyunghun commented on posting/views.py
> +    @non_user_accept_decorator
로그인과 상관없이 사용되는 view 같은데 데코레이터를 붙인 이유가 있을까요?

2021-03-10 01:07 UTC, exgaze commented on posting/urls.py
> +    path('/pagination/<int:posting_id>', DetailPaginationView.as_view()),
넵, 수정하겠습니다

2021-03-10 01:10 UTC, exgaze commented on posting/views.py
> +    @non_user_accept_decorator
연관된 포스팅들에도 좋아요 갯수와 유저가 좋아요를 눌렀는지 그렇지 않은지 표시해주어야 합니다. 그러기 위해선, 유저가 로그인한 상태인지 아닌지 우선 판별하고, 로그인을 했다면 연관된 포스팅 중 좋아요를 누른 포스팅들에 누른 상태임을 프론트가 알 수 있도록 Boolean값으로 전달해주어야 합니다. 그렇게 하기 위해서 로그인 데코레이터와 약간 다른 유저 판별 데코레이터를 추가 작성하였고, 그 데코레이터를 이용하여 로그인 하지 않은 상태이면 상태값을 모두 false로 전달하고, 로그인을 한 유저라면 그 유저가 연관된 포스팅들에 좋아요를 눌렀는지 아닌지를 True False를 부여하여 데이터를 반환하기 위해 작성하였습니다.

2021-03-10 07:15 UTC, Kang-kyunghun commented
LGTM~~!!

2021-03-10 07:15 UTC, merged